name: Docker Image Push to GHCR

on: 
  push

jobs: 
  build_and_publish: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Create environment file
        run: |
          echo POSTGRES_DB_NAME='${{ secrets.LINODE_DB_NAME }}' >> .env
          echo POSTGRES_PASSWORD='${{ secrets.LINODE_PG_PASSWORD }}' >> .env
          echo POSTGRES_USERNAME='${{ secrets.LINODE_PG_USERNAME }}' >> .env
      - name: Build and Push
        run: |
          docker login --username lincketheo --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . -t ghcr.io/lincketheo/events-backend-ghcr:latest
          docker push ghcr.io/lincketheo/events-backend-ghcr:latest
  deploy:
    needs: "build_and_publish"
    runs-on: ubuntu-latest
    steps:
      - name: Executing ssh command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LINODE_HOST }}
          username: ${{ secrets.LINODE_USERNAME }}
          key: ${{ secrets.LINODE_GITHUB_SSH_KEY }}
          port: ${{ secrets.LINODE_SSH_PORT }}
          script: echo '${{ secrets.LINODE_GITHUB_PASSWORD }}' | sudo -S systemctl restart communeo-api