name: Docker Image Push to GHCR

on: 
  push

jobs: 
  build_and_publish: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Build and Push
        run: |
          docker login --username lincketheo --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . -t ghcr.io/lincketheo/events-backend-ghcr:latest
          docker push ghcr.io/lincketheo/events-backend-ghcr:latest
  deploy:
    needs: "build_and_publish"
    runs-on: ubuntu-latest
    steps:
      - name: Executing ssh command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LINODE_HOST }}
          username: ${{ secrets.LINODE_USERNAME }}
          password: ${{ secrets.LINODE_PASSWORD }}
          port: ${{ secrets.LINODE_SSH_PORT }}
          script: bash run-docker.sh